site_name: My Personal Page
site_url: https://rainteacher.github.io/Mypage/

nav:
  - 首页: index.md
  - Operation Management:
      - Part1/index.md
      - 研究简介: Part1/File1.md
  - Operation Research:
      - Part2/index.md
      - 研究简介: Part2/File2.md
  - Reinforcement Learning:
      - Part3/index.md
      - 研究简介: Part3/File3.md
docs_dir: docs/

theme:
  name: null
  custom_dir: mkdocs_custommill
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html, index.html, css/base.css]
  search_index_only: true
  include_search_page: true
  home: usage
  main_color: "#bb0000"
  gray: "#d0d0d0"
  lighter_gray: "#eeeeee"
  date_time_format: "%Y-%m-%d %H:%M:%S %Z"
  toc_depth: 2